import {
    Activity,
    BarChart3,
    Bell,
    BookOpen,
    Building2,
    Calendar,
    ClipboardList,
    CreditCard,
    Database,
    FileText,
    Flag,
    Folder,
    FolderGit2,
    Globe,
    Home,
    Image,
    KeyRound,
    LayoutGrid,
    ListTree,
    Lock,
    Mail,
    MessageSquare,
    Package,
    Settings,
    ShieldCheck,
    ShoppingCart,
    Star,
    Tag,
    Users,
    Wrench,
    type LucideIcon,
} from 'lucide-react';

/**
 * Curated icon set selectable for a menu item. Keep in sync with
 * App\Models\Menu::ICONS on the backend.
 */
export const MENU_ICONS: Record<string, LucideIcon> = {
    LayoutGrid,
    Users,
    ShieldCheck,
    KeyRound,
    ListTree,
    Settings,
    FileText,
    Folder,
    FolderGit2,
    BookOpen,
    BarChart3,
    Bell,
    Calendar,
    Mail,
    MessageSquare,
    CreditCard,
    ShoppingCart,
    Package,
    Building2,
    Home,
    Database,
    Globe,
    Image,
    Tag,
    Star,
    Flag,
    Lock,
    Wrench,
    Activity,
    ClipboardList,
};

export function resolveMenuIcon(name: string | null): LucideIcon | null {
    return name ? (MENU_ICONS[name] ?? null) : null;
}
